services:
  # Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - gateway

  # Backend Services
  gateway:
    build:
      context: ./server/services/gateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT:-4000}:${GATEWAY_PORT:-4000}"
    volumes:
      - ./server/services/gateway:/app
      - /app/node_modules
    env_file:
      - .env
    command: npx ts-node-dev --respawn --transpile-only --poll src/index.ts
    environment:
      - NODE_ENV=development
    depends_on:
      - auth-service
    tty: true

  auth-service:
    build:
      context: ./server/services/auth-service
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT:-4001}:${AUTH_SERVICE_PORT:-4001}"
    volumes:
      - ./server/services/auth-service:/app
      - /app/node_modules
    env_file:
      - .env
    command: npx ts-node-dev --respawn --transpile-only --poll src/index.ts
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis
    tty: true

  user-service:
    build:
      context: ./server/services/user-service
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVICE_PORT:-4002}:${USER_SERVICE_PORT:-4002}"
    volumes:
      - ./server/services/user-service:/app
      - /app/node_modules
    env_file:
      - .env
    command: npx ts-node-dev --respawn --transpile-only --poll src/index.ts
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    tty: true

  # Databases and Caches
  postgres:
    image: postgres:latest
    container_name: app_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: app_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data:
