services:
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT:-4000}:${GATEWAY_PORT:-4000}"
    volumes:
      - ./services/gateway:/app
      - /app/node_modules
    env_file:
      - .env
    command: npx ts-node-dev --respawn --transpile-only --poll src/index.ts
    environment:
      - NODE_ENV=development
    tty: true

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT:-4001}:${AUTH_SERVICE_PORT:-4001}"
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    env_file:
      - .env
    command: npx ts-node-dev --respawn --transpile-only --poll src/index.ts
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    tty: true

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: auth_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
